events_in_oradea/events/urls.py
from django.urls import path

from . import views

app_name = 'events'
urlpatterns = [
    path('', views.index, name='index'),
	path('all_events/', views.all_events, name='all_events_template'),
	path('<int:pk>/', views.event_entry, name='event_entry_template'),
]

events_in_oradea/events_in_oradea/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('events/', include('events.urls')),
    url(r'^admin/', admin.site.urls),
]

events_in_oradea/events/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.

class Event(models.Model):
	event_title = models.CharField(max_length=300)
	event_preview = models.TextField(max_length=500, default='event preview')
	event_text = models.TextField(default='event text')
	event_start_time = models.DateTimeField(null=True, blank=True) 
	event_end_time = models.DateTimeField(null=True, blank=True)
	event_type = models.CharField(max_length=100,default='event type')
	event_location_lon = models.FloatField(default='21.928030')
	event_location_lat = models.FloatField(default='47.055500')
	event_URL = models.URLField(default='event url')
	event_price = models.IntegerField(default=0)
	event_image_url = models.URLField(default='image url')

	def __str__(self):
		return self.event_title	
	

events_in_oradea/events/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from .models import Event

# Create your views here.
def index(request):
	events = Event.objects.all()
	# event_types = events.event_type
	return render(request, 'events/index.html', {'events': events})





def all_events(request):
	events = Event.objects.all()
	return render(request, 'events/all_events_template.html', {'events': events})





def event_entry(request,pk):
	events = Event.objects.all()
	event = get_object_or_404(Event, pk=pk)
	return render(request, 'events/event_entry_template.html', {'events': events, 'event': event})

events_in_oradea/events/templates/events/all_events_template.html
{% extends "layout.html" %}

{% block content %}
<div class="container">
  <div class="row">

	{% for event in events %}
    <div class="col-sm-12 col-md-6 col-lg-4">
		
		<div class="card mb-2 mt-3">
			<a href="{% url 'events:event_entry_template' event.id %}" style="text-decoration: none; color: inherit;">
			<div class="card-header" style="font-size:0.8rem;"> {{article.category}} </div>
			<div style="width:100%; height:200px;">
				<img class="card-img-top" src="{{event.event_image_url}}" alt="event image" 
				style="width: 100%; height: 100%; object-fit: contain;">
			</div>
			<div class="card-body">
				<h4 class="card-title">{{event.event_title}}</h4>
				<p class="card-text"> {{event.event_preview}} </p>
				<a href="{% url 'events:event_entry_template' event.id %}" class="card-link" style="float: right;">Vezi eveniment</a>
			</div>
			</a>
		</div>
		
    </div>
	{% endfor %}
    
  </div>
</div>
{% endblock %}

events_in_oradea/events/templates/events/event_entry_template.html
{% extends "layout.html" %}

{% block content %}
<div class="container">
  <div class="row">

	{% if event %}
    <div class="col-sm-12">
		<div class="card mb-2 mt-3">
			<div class="card-header" style="font-size:0.8rem;"> {{event.event_type}} </div>
			<div class="card-header" style="font-size:0.8rem; color: red;"> 
				<b>{{event.event_start_time}}  &nbsp&nbsp -  &nbsp&nbsp {{event.event_end_time}}</b>
			</div>

			<div style="width:100%; height:400px;">
			<span class="badge badge-warning" style="margin: 1%;">Preţ: {{event.event_price}} RON</span><br>

				<img class="card-img-top" src="{{event.event_image_url}}" alt="event image" 
				style="width: 100%; height: 100%; object-fit: contain;">

			</div><br><br>
			<div class="card-body">
				<h4 class="card-title">{{event.event_title}}</h4>
				<p class="card-text card-header"> {{event.event_preview}} </p><hr>
				<p class="card-text" style="color:#4F4F4F;"> {{event.event_text}} </p>

				<a href="{{event.event_URL}}" class="btn btn-lg btn-success btn-block">
					Vezi Site-ul Evenimentului
				</a><br>
				<a href="{% url 'events:index' %}" class="card-link" style="float: right;">Acasă</a>
			</div>
		</div>
    </div>
	{% endif %}
    
  </div>
</div>
{% endblock %}

events_in_oradea/events/templates/events/index.html
{% extends "layout.html" %}

{% block content %}

<div id="googleMap" style="width:100%;height:100vh;"></div>

<script>
function myMap() {
var mapProp= {
  center:new google.maps.LatLng(51.508742,-0.120850),
  zoom:5,
};
var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD-jz8KpW678C3Z72YItgcLyzyt95jcR2Q&callback=myMap"></script>

{% endblock %}

events_in_oradea/templates/layout.html
{% load static from staticfiles %}

<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

<link rel="icon" href='{% static "NewsList/logo1.ico" %}'>
<title>Events in Oradea</title>
</head>
<body style="background-color:#B47931">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="{% url 'events:index' %}">
	<img src="{% static "events/logo.png" %}" height="60" class="d-inline-block align-top" alt="">
	Evenimente în Oradea
	</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav text-md-center nav-justified w-100">
			<li class="nav-item" style="padding: 0 5%;">
				<a class="nav-link" href="#">despre noi</a>
			</li>
			<li class="nav-item" style="padding: 0 5%;">
				<a class="nav-link" href="{% url 'events:all_events_template'%}">vezi toate evenimentele</a>
			</li>
			<li class="nav-item" style="padding: 0 5%;">
				<a class="nav-link" href="#">filtreaza evenimente</a>
			</li>
		</ul>
	</div>
</nav>

{% block content %}{% endblock %}

<!-- Optional JavaScript for Bootstrap -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
</body>
</html>